[package]
name = "airspy"
version = "0.2.0"
authors = ["Andres Vahter <andres.vahter@gmail.com>"]

[dependencies]
libc = "*"
log = "*"

fern = "*"
time = "*"

[dependencies.ipc]
git = "https://github.com/alexcrichton/ipc-rs"
